# https://medium.com/flutter-community/managing-multi-package-flutter-projects-with-melos-c8ce96fa7c82
name: remainder

packages:
  - layers/app/**
  - layers/data/**
  - layers/domain/**
  - layers/features/**
  - '*'

ignore:
  - code_generator

scripts:

  analyze:
    run: melos exec -- flutter analyze .
    description: Run `flutter analyze` in all packages.

  get:
    run: |
      flutter pub get
      melos exec --concurrency=1 --fail-fast --no-flutter -- pub get
      melos exec --concurrency=1 --fail-fast --flutter -- flutter pub get
    description: Get all Dart and Flutter package dependencies across the workspace.

  clean:
    run: |
      flutter clean
      melos exec -- flutter clean
    description: Clean build artifacts in the root and all packages.

  clean_micro_init:
    run: |
      find . -type f -name 'micro_init.module.dart' -delete
    description: Deletes all micro_init.module.dart files from every package/module

  builder:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    select-package:
      scope:
        - core
        - app_bloc
        - navigation
        - backend_services
        - database
        - notification
        - repository
        - usecase
    description: Run build_runner generation

  builder_ui:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    select-package:
      scope:
        - entry_feature
        - feature_home
        - feature_local_auth
    description: Run build_runner generation

  run_default_app:
    run: melos exec --scope=app_bloc -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for app_bloc

  builder_app_bloc:
    run: melos exec --scope=app_bloc -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for app_bloc

  builder_navigation:
    run: melos exec --scope=navigation -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for navigation

  builder_backend_services:
    run: melos exec --scope=backend_services -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for backend_services

  builder_database:
    run: melos exec --scope=database -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for database

  builder_notification:
    run: melos exec --scope=notification -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for notification

  builder_core:
    run: melos exec --scope=core -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for core

  builder_repository:
    run: melos exec --scope=repository -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for repository

  builder_usecase:
    run: melos exec --scope=usecase -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner generation for usecase
